Add vue-loader and template support
cezaraugusto/extension.js pull request #61
Opened 2024-05-15 08:03 UTC by OSpoon

I added the necessary modules `vue-loader`, `ts-loader`, and `@vue/compiler-sfc` in `programs/develop`. Additionally, I have added vue and vue-typescript templates. 

Now, using the vue and vue-typescript templates, we can achieve the same presentation effect as with the react and react-typescript templates.

When you have time, please give me some suggestions. I would be very happy.

2024-05-16 19:43 UTC, cezaraugusto requested changes
Hi @OSpoon, this is a huge progress towards Vue support, thanks a lot! I got able to create and start the project using both templates! 🧩

There are a few changes I left in the comments. I also need you to please update the dev-server in [this line](https://github.com/cezaraugusto/extension.js/blob/main/programs/develop/webpack/webpack-dev-server.ts#L30) to set watchFiles to `undefined` not only for React but also Vue extensions. This way we can get true hot-module replacement for `.vue` files.

Hot-module replacement isn't working for `content_scripts`, unfortunately (using `vue-typescript` template).  It is not a blocker to land these changes and have at least partial support for Vue, but if you any existing config that managed to do this, I'd love to know and find ways to add it to a future patch.

2024-05-16 19:43 UTC, cezaraugusto commented on programs/create/templates/vue-typescript/template/content/ContentApp.vue
When I try to edit this file I get the following error in the console, and the content_script doesn't reload after changes. Do you have any hints?

<img width="677" alt="Screenshot 2024-05-16 at 16 22 23" src="https://github.com/cezaraugusto/extension.js/assets/4672033/af51a108-8e85-4cf4-b6ae-982e4ca67c4f">

2024-05-17 05:27 UTC, OSpoon commented on programs/develop/webpack/loaders/vueLoaders.ts
> +      exclude: /background\.ts/,
Just like the error you encountered, it was still exposed during the hot update phase, but this error seemed to be just a type inconsistency problem, so I decided to enable the [transpileonly](https://github.com/TypeStrong/ts-loader#transpileonly) option to skip type checking.

Although transpileOnly will default to true after using [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin), it still seems to need to be turned on explicitly.

2024-05-17 05:29 UTC, OSpoon commented on programs/create/templates/vue-typescript/template/content/ContentApp.vue
I considered explicitly enabling [transpileonly](https://github.com/TypeStrong/ts-loader#transpileonly) to skip type checking.

2024-05-17 05:32 UTC, OSpoon commented on programs/develop/webpack/loaders/vueLoaders.ts
> +      loader: 'vue-loader'
I agree.

2024-05-17 05:33 UTC, OSpoon commented on programs/develop/webpack/loaders/vueLoaders.ts
> +      loader: 'ts-loader',
I agree.

2024-05-17 05:34 UTC, OSpoon commented on programs/develop/webpack/loaders/vueLoaders.ts
> +    vueLoaders.push({
I will narrow the scope of influence.

2024-05-17 05:44 UTC, OSpoon commented on programs/create/templates/vue-typescript/template/content/content/ContentApp.vue
I agree.

2024-05-17 06:14 UTC, OSpoon commented on programs/develop/webpack/webpack-config.ts
> +        ...vueLoaders(projectPath),
I agree.

2024-05-17 06:30 UTC, OSpoon commented on programs/develop/webpack/loaders/vueLoaders.ts
> +      exclude: /background\.ts/,
In [cli-plugin-typescript/index.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-typescript/index.js#L64C9-L64C22) has the same configuration.

2024-05-19 01:50 UTC, cezaraugusto commented on programs/develop/webpack/loaders/vueLoaders.ts
> +      exclude: /background\.ts/,
sounds good

2024-05-19 01:53 UTC, cezaraugusto approved these changes
LGTM ++

Thanks a lot for your contribution, @OSpoon! Will ensure this is added in the next release.

2024-05-19 01:53 UTC, merged